export const EDIT_STATE = {
  INIT: 'INIT',
  INSERTING: 'INSERTING',
  POSSIBLE: 'POSSIBLE',
  VALIDATING: 'VALIDATING',
}

export const EDIT_PAGE_MODE = {
  CREATE: 'CREATE',
  MODIFY: 'MODIFY',
  DETAIL: 'DETAIL',
  DELETE: 'DELETE',
}

export const EDIT_VALID_TEXT_LENGTH = 3
